package class11;

public class Execeptiondemo {
	public static void main(String args[]){  
		   try{
		   }catch(ArithmeticException e){System.out.println(e);}   
		   //rest code of the program   
		   System.out.println("code after exception...");  
		  }

}
